# Day - 19 python built in functions + Numpy

In [ ]:
def square(x):
    return x*x


In [ ]:
square(3)

9

In [ ]:
square_lambda = lambda x: x*x

In [ ]:
square_lambda(3)

9

In [ ]:
square_lambda = lambda x: print(x*x, "hello")

In [ ]:
square_lambda(3)

9 hello


In [ ]:
add_lambda = lambda x,y,z : x+y+z

In [ ]:
add_lambda(1,2,3)

6

# Sort

In [ ]:
a = [1,2,110,-3,5,6,90,78]

In [ ]:
a.sort()
a

[-3, 1, 2, 5, 6, 78, 90, 110]

# Sorted

In [ ]:
a = [1,2,110,-3,5,6,90,78]

In [ ]:
sorted_a = sorted(a)

In [ ]:
sorted_a


[-3, 1, 2, 5, 6, 78, 90, 110]

# using key = in both sort and sorted

In [ ]:
words = ["apple","kiwi","banana"]
#apple = 5
#Kiwi = 4
#Banana =6

In [ ]:
words.sort(key=len)

In [ ]:
words

['kiwi', 'apple', 'banana']

In [ ]:
words_sort = ["apple","kiwi","banana"]


In [ ]:
print(sorted(words_sort,key=len))

['kiwi', 'apple', 'banana']


In [ ]:
words_sort = ["apple","kiwi","banana"]
print(sorted(words_sort,key=lambda x: x[-1]))

['banana', 'apple', 'kiwi']


In [ ]:
def get_last_char(x):
    return x[-1]

In [ ]:
words_sort = ["apple","kiwi","banana"]
# apple = e
# kiwi = i
# banana = a 
# sort bt last letter
print(sorted(words_sort,key=get_last_char))
print(sorted(words_sort,key=get_last_char,reverse=True))


['banana', 'apple', 'kiwi']
['kiwi', 'apple', 'banana']


In [ ]:
a_dict = {
    1: "hello",
    100: "bye",
    2:"How are you !"
}

In [ ]:
print(sorted(a_dict.keys(),reverse=True))

[100, 2, 1]


# map()

# syntax map(any function, iterable)

In [ ]:
square = lambda x: x*x

In [ ]:
square(2)

4

In [ ]:
num = list(range(0,11))

In [ ]:
num

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
map(square,num)

In [ ]:
result = list(map(square,num))

In [ ]:
result

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
result = list(map(lambda x: x*x,num))

In [ ]:
result

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
add_lambda = lambda x,y:x+y

In [ ]:
add_lambda(1,2)

3

In [ ]:
add_lambda = lambda item:item[0]+item[1]

In [ ]:
add_lambda((1,2))

3

In [ ]:
a_list = [(1,2),(3,4),(5,6)]

In [ ]:
result = list(map(add_lambda,a_list))

In [ ]:
result

[3, 7, 11]

# Zip

In [ ]:
names = ["norma","gagan",1]
scores = [10,100]

In [ ]:
print(list(zip(names,scores)))

[('norma', 10), ('gagan', 100)]


In [ ]:
for i in zip(names,scores):
    print(i)

('norma', 10)
('gagan', 100)


In [ ]:
dict(zip(names,scores))

{'norma': 10, 'gagan': 100}

# Unpacking

In [ ]:
a = [1,2,3,4,5,6]

In [ ]:
print(a)

[1, 2, 3, 4, 5, 6]


In [ ]:
print(*a) # unpacking

1 2 3 4 5 6


In [ ]:
def add(a,b,c):
    print(a+b+c)

In [ ]:
add(1,2,3)

6


In [ ]:
a = [1,2,3]

In [ ]:
add(a)

TypeError: add() missing 2 required positional arguments: 'b' and 'c'

In [ ]:
add(*a)

6


In [ ]:
num = [(1,"mondal"),(2,"hello")]

In [ ]:
print(*num)

(1, 'mondal') (2, 'hello')


In [ ]:
name,scores = zip(*num)

In [ ]:
print(name)
print(scores)

(1, 2)
('mondal', 'hello')


# list comprhension

In [ ]:
num = [1,1,1,1,1,2,3,4,1,11,34,1]

# syntax of list comphrension
# expresion for item in ietrable if conditio

In [ ]:
new_res = []
for i in num:
    if i == 1:
        new_res.append(i)
print(new_res)        

[1, 1, 1, 1, 1, 1, 1]


In [ ]:
new_res = [i for i in num if i == 1]

In [ ]:
print(new_res)

[1, 1, 1, 1, 1, 1, 1]


#ps sqaure of numbers

In [ ]:
new_res = []
for i in num:
    new_res.append(i*i)
print(new_res)    

[1, 1, 1, 1, 1, 4, 9, 16, 1, 121, 1156, 1]


In [ ]:
new_res = [i*i for i in num]

In [ ]:
print(new_res)

[1, 1, 1, 1, 1, 4, 9, 16, 1, 121, 1156, 1]


# if numb i sven and double it

In [ ]:
a_lst = [1,2,3,4,5,6,7,8,9]

In [ ]:
new_res_even = [i*i for i in a_lst if i%2==0]

In [ ]:
print(new_res_even)

[4, 16, 36, 64]


In [ ]:
new_res_odd = [i*i for i in a_lst if i%2==1]

In [ ]:
print(new_res_odd)

[1, 9, 25, 49, 81]


In [ ]:
new_res_lam_even = [lambda i=i: i*i for i in a_lst if i%2==0]

In [ ]:
print(new_res_lam_even)

[<function <lambda> at 0x000002417B1B62A0>, <function <lambda> at 0x000002417B1B7880>, <function <lambda> at 0x000002417B1B4680>, <function <lambda> at 0x000002417B1B7CE0>]


In [ ]:
for f in new_res_lam_even:
    print(f())

4
16
36
64


# Dictionary comprehensive
# key Expression , value Expression


In [ ]:
names = ["norma","gagan",1]
scores = [10,100]

In [ ]:
result = {names, scores for name,score in zip(names,scores)}

SyntaxError: did you forget parentheses around the comprehension target? (532113355.py, line 1)

# Numpy

In [ ]:
! pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -------------- ------------------------- 4.5/12.6 MB 24.4 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.6 MB 24.8 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 23.3 MB/s eta 0:00:00


In [2]:
import numpy as np
import time

In [ ]:

def time_it(func):
    def wrapper(*args):
        start_t = time.time()
        func(*args)
        end_t = time.time()
        time_taken = end_t-start_t
        print(f"Time taken {time_taken}")
    return wrapper    

In [ ]:
@time_it
def python_add():
    a = list(range(1000000))
    b = list(range(1000000))
    c = [x+y for x,y in zip(a,b)]

In [ ]:
time_taken = python_add()

Time taken 0.37226438522338867


# traditional way

In [6]:
a = list(range(10000000))
b = list(range(10000000))

start_t = time.time()
c = [x+y for x,y in zip(a,b)]
# print(c)
end_t = time.time()
time_taken = end_t-start_t
print(f"Time taken {time_taken}")

Time taken 0.6695010662078857


# in Numpy version

In [9]:
a = list(range(10000000))
b = list(range(10000000))
a = np.array(a)
b = np.array(b)

start_t = time.time()
c = a+b
# print(c)
end_t = time.time()
time_taken = end_t-start_t
print(f"Time taken {time_taken}")

Time taken 0.034494638442993164


# np range
# arange(start,stop,step)

In [10]:
print(np.arange(5))

[0 1 2 3 4]


In [14]:
print(np.arange(1,10,2))
np_arange = np.arange(1,10,2)
print(type(np_arange))

[1 3 5 7 9]
<class 'numpy.ndarray'>


# np.linespace(start,stop, num =x)

In [26]:
np_linespace = np.linspace(1,100,10)
print(type(np_linespace))
print(np_linespace)   # diff between each number 11 for 10 count

<class 'numpy.ndarray'>
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [27]:
for i in np.linspace(1,10,10):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


# np.zeros(shape)

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

# List

In [30]:
a = [1,2,3]
print(a)

[1, 2, 3]


In [33]:
a = [[1,2,3],[2,2,3]]
a[0]

[1, 2, 3]

In [34]:
a[1]

[2, 2, 3]

In [36]:
npz= np.zeros(5)


In [37]:
npz.ndim

1

In [47]:
npz_2d= np.zeros((5,5))

In [48]:
npz_2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
npz_2d.ndim

2

In [50]:
npz_3d= np.zeros((5,5,5))

In [51]:
npz_3d

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [52]:
npz_3d.ndim

3