# Numpy Math opertaions

In [2]:
a =[1,2,3]
b=[4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [3]:
import numpy as np

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [7]:
a-b

array([-3, -3, -3])

In [8]:
a/b

array([0.25, 0.4 , 0.5 ])

# Comparison

In [9]:
print(a>b)

[False False False]


In [10]:
print(a==b)

[False False False]


# logical operators


In [11]:
x = np.array([True, False, True])
y = np.array([True, False, False])

print(np.logical_and(x,y))

[ True False False]


# Bitwise OPerators

In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.bitwise_and(a,b))

[0 0 2]


# scalar oprtaions

In [ ]:
celcius = np.array([0,10,20,30])


print(celcius * 9 /5 +32) # to_farenheit

[32. 50. 68. 86.]


In [18]:
celcius = [0,10,20,30] # in python this is not possible


print(celcius * 9 /5 +32) # to_farenheit

TypeError: unsupported operand type(s) for /: 'list' and 'int'

# common math ops


In [19]:
a = np.array([1,2,3,4])

In [ ]:
print(np.sqrt(a))
print(np.exp(a)) # e^1 e value It's approximately 2.71828

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


# Matrix operation

# element wise oprtaions 

In [22]:
units = np.array([100,200,150])
profit = np.array([10,20,30])

In [23]:
units*profit

array([1000, 4000, 4500])

# Dot Product

In [25]:
# sqft
# bedrooms
# location  = 1 is good 0 is bad

# ouput - predict the price

In [32]:
house = np.array([1200,3,1])

In [33]:
house.shape

(3,)

In [34]:
w = np.array([200,10000,50000])

In [ ]:
w.shape1

(3,)

In [37]:
print(np.dot(house,w))

320000


In [40]:
house = np.array([[1200,3,1],
                 [1200,2,0],
                 [2400,4,2]])
w = np.array([200,10000,50000])

In [41]:
print(np.dot(house,w))

[320000 260000 620000]


In [43]:
print(house @ w) # @ represent Dot Product

[320000 260000 620000]
